version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: busstalker-dev
    command: node busController.js
    volumes:
      - .:/usr/app/
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
